// Explicit revision-3 strategy. Targets are natural stats; see docs/STRATEGY.md.
::BroLedger.Builds <- [
    {
        id = "shield_tank_nimble",
        label = "Shield Tank - Nimble",
        role = "Tank",
        weaponTags = ["Shield"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.shield_expert", "perk.indomitable", "perk.nimble"],
        niche = "Hold enemies with defence, Resolve and usable Fatigue; attacks are incidental.",
        targets = {hp = 84, fatigue = 110, resolve = 60, mdef = 35},
        preferred = {hp = 100, fatigue = 120, resolve = 70, mdef = 40, initiative = 110},
        priority = ["mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.shield_expert", "perk.nimble", "perk.underdog", "perk.indomitable", "perk.pathfinder", "perk.fortified_mind"],
        swaps = [],
        armour = "nimble",
        weapons = "Shield + utility spear or dagger. Choose the lightest useful weapon; the tank does not need offensive training.",
        masteryNote = "Skipped: defensive actions take priority over attacks. A spear is useful without Spear Mastery.",
        note = "Shieldwall + Indomitable costs the whole turn. Recover needs a separate turn. Natural defence and Resolve define fit; shield and Dodge bonuses are not graded.",
        patterns = [
            {label = "Shieldwall + Indomitable; Recover needs a separate turn", steps = [{ids = ["actives.shieldwall"], count = 1, fat = 20, ap = 4, mastery = ""}, {ids = ["actives.indomitable"], count = 1, fat = 25, ap = 5, mastery = ""}], turns = 2, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "shield_tank_forged",
        label = "Shield Tank - Battle Forged",
        role = "Tank",
        weaponTags = ["Shield"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.shield_expert", "perk.indomitable", "perk.battle_forged"],
        niche = "Hold enemies with defence, Resolve and usable Fatigue; attacks are incidental.",
        targets = {hp = 80, fatigue = 135, resolve = 65, mdef = 40},
        preferred = {hp = 90, fatigue = 145, resolve = 75, mdef = 45},
        priority = ["mdef", "resolve", "fatigue", "hp"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.shield_expert", "perk.brawny", "perk.battle_forged", "perk.underdog", "perk.recover", "perk.indomitable", "perk.steel_brow"],
        swaps = [],
        armour = "battle_forged",
        weapons = "Shield + utility spear or dagger. Choose the lightest useful weapon; the tank does not need offensive training.",
        masteryNote = "Skipped: defensive actions take priority over attacks. A spear is useful without Spear Mastery.",
        note = "Shieldwall + Indomitable costs the whole turn. Recover needs a separate turn. Natural defence and Resolve define fit; shield and Dodge bonuses are not graded.",
        patterns = [
            {label = "Shieldwall + Indomitable; Recover needs a separate turn", steps = [{ids = ["actives.shieldwall"], count = 1, fat = 20, ap = 4, mastery = ""}, {ids = ["actives.indomitable"], count = 1, fat = 25, ap = 5, mastery = ""}], turns = 2, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "tempo_spear",
        label = "Tempo Shield Fighter - Spear",
        role = "Shield fighter",
        weaponTags = ["Spear", "Shield"],
        stopgap = true,
        flex = ["perk.gifted"],
        identity = ["perk.fast_adaption", "perk.nimble"],
        niche = "Early stopgap: reliable attacks while retaining a shield.",
        targets = {hp = 60, fatigue = 90, resolve = 40, matk = 60, mdef = 10},
        preferred = {hp = 72, fatigue = 100, resolve = 45, matk = 70, mdef = 22},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.fast_adaption", "perk.colossus", "perk.nine_lives", "perk.dodge", "perk.gifted", "perk.nimble", "perk.shield_expert", "perk.rotation", "perk.underdog", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Spear + Shield; Fighting Spear is the standard example.",
        masteryNote = "Skipped: the ordinary attack accuracy bonus needs no mastery. Spend early perks on reliability and survival.",
        note = "Early fit is not an endgame strength ranking. A shield sacrifices Double Grip. Use the conditional weapon examples to weigh accuracy against damage; no universal switch level applies.",
        patterns = [
            {label = "Two ordinary attacks; shield held", steps = [{ids = ["actives.thrust"], count = 2, fat = 10, ap = 4, mastery = ""}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "tempo_sword",
        label = "Tempo Shield Fighter - Sword",
        role = "Shield fighter",
        weaponTags = ["Sword", "Shield"],
        stopgap = true,
        flex = ["perk.gifted"],
        identity = ["perk.fast_adaption", "perk.nimble"],
        niche = "Early stopgap: reliable attacks while retaining a shield.",
        targets = {hp = 60, fatigue = 90, resolve = 40, matk = 70, mdef = 10},
        preferred = {hp = 72, fatigue = 100, resolve = 45, matk = 80, mdef = 22},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.fast_adaption", "perk.colossus", "perk.nine_lives", "perk.dodge", "perk.gifted", "perk.nimble", "perk.shield_expert", "perk.rotation", "perk.underdog", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Sword + Shield; compare Arming Sword and Noble Sword separately.",
        masteryNote = "Skipped: the ordinary attack accuracy bonus needs no mastery. Spend early perks on reliability and survival.",
        note = "Early fit is not an endgame strength ranking. A shield sacrifices Double Grip. Use the conditional weapon examples to weigh accuracy against damage; no universal switch level applies.",
        patterns = [
            {label = "Two ordinary attacks; shield held", steps = [{ids = ["actives.slash"], count = 2, fat = 10, ap = 4, mastery = ""}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "tempo_flail",
        label = "Tempo Shield Fighter - Flail",
        role = "Shield fighter",
        weaponTags = ["Flail", "Shield"],
        stopgap = true,
        flex = ["perk.gifted"],
        identity = ["perk.mastery.flail"],
        niche = "Early stopgap: reliable attacks while retaining a shield.",
        targets = {hp = 60, fatigue = 100, resolve = 40, matk = 70, mdef = 10},
        preferred = {hp = 72, fatigue = 115, resolve = 45, matk = 80, mdef = 22},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.fast_adaption", "perk.colossus", "perk.nine_lives", "perk.dodge", "perk.gifted", "perk.nimble", "perk.shield_expert", "perk.mastery.flail", "perk.underdog", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Flail + Shield; use Lash against exposed heads when its Fatigue cost is affordable.",
        masteryNote = "Taken: cheaper attacks and shield bypass on Lash.",
        note = "Early fit is not an endgame strength ranking. A shield sacrifices Double Grip. Ordinary flail attacks bypass the shield item defence, but not Shieldwall; mastery also helps Lash.",
        patterns = [
            {label = "Two ordinary attacks; shield held", steps = [{ids = ["actives.flail"], count = 2, fat = 13, ap = 4, mastery = "perk.mastery.flail"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "shield_mace",
        label = "Shield Control - Mace",
        role = "Shield fighter",
        weaponTags = ["Mace", "Shield"],
        stopgap = false,
        flex = ["perk.gifted"],
        identity = ["perk.mastery.mace"],
        niche = "Accurate shield support: deny enemy actions with stuns.",
        targets = {hp = 75, fatigue = 110, resolve = 50, matk = 75, mdef = 25},
        preferred = {hp = 85, fatigue = 125, resolve = 60, matk = 85, mdef = 35},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.shield_expert", "perk.mastery.mace", "perk.nimble", "perk.underdog", "perk.rotation", "perk.fortified_mind", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Winged Mace + Shield.",
        masteryNote = "Taken: stun succeeds after a landed hit against susceptible enemies, with reduced Fatigue.",
        note = "Stun immunity and a missed hit still defeat control. Mastery does not give a guaranteed hit.",
        patterns = [
            {label = "Two stun attempts; susceptible targets must be hit", steps = [{ids = ["actives.knock_out"], count = 2, fat = 25, ap = 4, mastery = "perk.mastery.mace"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "shield_hammer",
        label = "Shield Armour Breaker - Hammer",
        role = "Shield fighter",
        weaponTags = ["Hammer", "Shield"],
        stopgap = false,
        flex = ["perk.gifted"],
        identity = ["perk.mastery.hammer"],
        niche = "Accurate shield support: strip armour for the company.",
        targets = {hp = 75, fatigue = 115, resolve = 50, matk = 80, mdef = 25},
        preferred = {hp = 85, fatigue = 130, resolve = 60, matk = 90, mdef = 35},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.shield_expert", "perk.mastery.hammer", "perk.nimble", "perk.underdog", "perk.rotation", "perk.fortified_mind", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Warhammer + Shield.",
        masteryNote = "Taken: Destroy Armor improves from a 1.5x to 2x armour multiplier, and costs less Fatigue.",
        note = "Destroy Armor trades ordinary HP damage for armour removal. A Hammer Duelist generally prefers ordinary Batter for penetrating HP damage.",
        patterns = [
            {label = "Two Destroy Armor attacks; allies exploit the opening", steps = [{ids = ["actives.crush_armor"], count = 2, fat = 25, ap = 4, mastery = "perk.mastery.hammer"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "spearwall",
        label = "Spearwall Specialist - Spear + Shield",
        role = "Shield fighter",
        weaponTags = ["Spear", "Shield"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.mastery.spear"],
        niche = "Zone enemies before contact; repeated reliable hits and a substantial reserve matter.",
        targets = {hp = 80, fatigue = 120, resolve = 50, matk = 80, mdef = 30},
        preferred = {hp = 90, fatigue = 135, resolve = 60, matk = 90, mdef = 40},
        priority = ["mdef", "hp", "resolve", "fatigue", "matk"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.shield_expert", "perk.mastery.spear", "perk.nimble", "perk.underdog", "perk.fortified_mind", "perk.pathfinder", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Fighting Spear + Shield. Spetum is a conditional alternative that gives up the shield and changes reach and action costs.",
        masteryNote = "Taken: cheaper Spearwall; breaches no longer disable it and it can be activated while engaged.",
        note = "Spearwall reaction attacks deal half damage. Enemy approaches are not guaranteed, misses allow breaches, and reactive attacks need additional Fatigue beyond the activation budget.",
        patterns = [
            {label = "Activate Spearwall; repeated incoming thrusts cost additional Fatigue", steps = [{ids = ["actives.spearwall"], count = 1, fat = 30, ap = 4, mastery = "perk.mastery.spear"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_2h_axe",
        label = "Centre Fighter - 2H Axe (Nimble)",
        role = "Two-handed",
        weaponTags = ["Axe"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.axe"],
        niche = "Accessible centre damage with a matching reach weapon; avoid prolonged surrounded contact.",
        targets = {hp = 72, fatigue = 100, resolve = 45, matk = 80, mdef = 22},
        preferred = {hp = 85, fatigue = 110, resolve = 50, matk = 90, mdef = 35, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.pathfinder", "perk.dodge", "perk.quick_hands", "perk.gifted", "perk.nimble", "perk.mastery.axe", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Greataxe + Longaxe. Quick Hands gives one eligible free swap per turn.",
        masteryNote = "Taken: ordinary attacks cost 12 rather than 15 Fatigue; the matching reach weapon shares the mastery.",
        note = "This centre route trades Underdog for offensive flexibility. Burst attacks require a kill and enough usable Fatigue. The natural targets can legitimately match the other centre weapon.",
        patterns = [
            {label = "One ordinary 2H attack; no kill assumed", steps = [{ids = ["actives.split_man"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.axe"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Two attacks; one kill must fund Berserk", steps = [{ids = ["actives.split_man"], count = 2, fat = 15, ap = 6, mastery = "perk.mastery.axe"}], turns = 3, buffer = 0, move = 0, kill = true},
        ],
    },
    {
        id = "forged_neutral_axe",
        label = "Fatigue-Neutral - 2H Axe (Battle Forged)",
        role = "Two-handed",
        weaponTags = ["Axe"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.battle_forged", "perk.mastery.axe"],
        niche = "Heavy-armour contact with one attack and movement; requires strong natural defence.",
        targets = {hp = 80, fatigue = 105, resolve = 40, matk = 82, mdef = 35},
        preferred = {hp = 90, fatigue = 110, resolve = 50, matk = 90, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.fortified_mind", "perk.quick_hands", "perk.mastery.axe", "perk.battle_forged", "perk.gifted", "perk.underdog", "perk.steel_brow", "perk.fearsome"],
        swaps = [],
        armour = "battle_forged",
        weapons = "Greataxe + Longaxe.",
        masteryNote = "Taken with Pathfinder: a 12-Fatigue attack plus ordinary movement fits normal 15 recovery.",
        note = "Only fatigue-neutral when actual recovery and equipment support the cycle. Incoming hits, injuries and terrain can change its economy; reserve capacity is still needed.",
        patterns = [
            {label = "One 2H attack + one flat tile (at most 3 Fatigue / 2 AP)", steps = [{ids = ["actives.split_man"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.axe"}], turns = 3, buffer = 10, move = 3, kill = false},
        ],
    },
    {
        id = "nimble_2h_mace",
        label = "Centre Fighter - 2H Mace (Nimble)",
        role = "Two-handed",
        weaponTags = ["Mace"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.mace"],
        niche = "Accessible centre damage with a matching reach weapon; avoid prolonged surrounded contact.",
        targets = {hp = 72, fatigue = 100, resolve = 45, matk = 80, mdef = 22},
        preferred = {hp = 85, fatigue = 110, resolve = 50, matk = 90, mdef = 35, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.pathfinder", "perk.dodge", "perk.quick_hands", "perk.gifted", "perk.nimble", "perk.mastery.mace", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Two-Handed Mace + Polemace. Quick Hands gives one eligible free swap per turn.",
        masteryNote = "Taken: ordinary attacks cost 12 rather than 15 Fatigue; the matching reach weapon shares the mastery.",
        note = "This centre route trades Underdog for offensive flexibility. Burst attacks require a kill and enough usable Fatigue. The natural targets can legitimately match the other centre weapon.",
        patterns = [
            {label = "One ordinary 2H attack; no kill assumed", steps = [{ids = ["actives.cudgel"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.mace"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Two attacks; one kill must fund Berserk", steps = [{ids = ["actives.cudgel"], count = 2, fat = 15, ap = 6, mastery = "perk.mastery.mace"}], turns = 3, buffer = 0, move = 0, kill = true},
        ],
    },
    {
        id = "forged_neutral_mace",
        label = "Fatigue-Neutral - 2H Mace (Battle Forged)",
        role = "Two-handed",
        weaponTags = ["Mace"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.battle_forged", "perk.mastery.mace"],
        niche = "Heavy-armour contact with one attack and movement; requires strong natural defence.",
        targets = {hp = 80, fatigue = 105, resolve = 40, matk = 82, mdef = 35},
        preferred = {hp = 90, fatigue = 110, resolve = 50, matk = 90, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.fortified_mind", "perk.quick_hands", "perk.mastery.mace", "perk.battle_forged", "perk.gifted", "perk.underdog", "perk.steel_brow", "perk.fearsome"],
        swaps = [],
        armour = "battle_forged",
        weapons = "Two-Handed Mace + Polemace.",
        masteryNote = "Taken with Pathfinder: a 12-Fatigue attack plus ordinary movement fits normal 15 recovery.",
        note = "Only fatigue-neutral when actual recovery and equipment support the cycle. Incoming hits, injuries and terrain can change its economy; reserve capacity is still needed.",
        patterns = [
            {label = "One 2H attack + one flat tile (at most 3 Fatigue / 2 AP)", steps = [{ids = ["actives.cudgel"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.mace"}], turns = 3, buffer = 10, move = 3, kill = false},
        ],
    },
    {
        id = "bf_2h_hammer_berserk",
        label = "Flank Breaker - 2H Hammer (Battle Forged)",
        role = "Two-handed",
        weaponTags = ["Hammer"],
        stopgap = false,
        flex = ["perk.killing_frenzy", "perk.pathfinder"],
        identity = ["perk.mastery.hammer"],
        niche = "Premium armoured flank breaker; Shatter needs accuracy, Fatigue and safe target access.",
        targets = {hp = 80, fatigue = 125, resolve = 45, matk = 85, mdef = 37},
        preferred = {hp = 90, fatigue = 145, resolve = 60, matk = 95, mdef = 45},
        priority = ["matk", "mdef", "fatigue", "hp", "resolve"],
        route = ["perk.colossus", "perk.pathfinder", "perk.steel_brow", "perk.quick_hands", "perk.mastery.hammer", "perk.battle_forged", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "battle_forged",
        weapons = "Two-Handed Hammer; optional Polehammer uses Hammer Mastery, not Polearm Mastery.",
        masteryNote = "Taken: Shatter gains 5 accuracy and its cost falls from 30 to 23 Fatigue; Smite falls to 12.",
        note = "Do not assume three Shatter targets, maximum Reach Advantage or a Berserk kill. Reach stacks require hits and are lost on weapon swaps.",
        patterns = [
            {label = "Shatter + Smite; one kill must fund Berserk", steps = [{ids = ["actives.shatter"], count = 1, fat = 30, ap = 6, mastery = "perk.mastery.hammer"}, {ids = ["actives.smite"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.hammer"}], turns = 3, buffer = 0, move = 0, kill = true},
            {label = "Single Shatter; reserve for a crowded flank", steps = [{ids = ["actives.shatter"], count = 1, fat = 30, ap = 6, mastery = "perk.mastery.hammer"}], turns = 3, buffer = 10, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_greatsword",
        label = "Damage - Greatsword (Nimble)",
        role = "Two-handed",
        weaponTags = ["Sword"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.sword"],
        niche = "Dedicated Greatsword damage with Fatigue for repeated attacks.",
        targets = {hp = 80, fatigue = 115, resolve = 45, matk = 80, mdef = 30},
        preferred = {hp = 90, fatigue = 130, resolve = 55, matk = 90, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.pathfinder", "perk.mastery.sword", "perk.nimble", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Greatsword; Overhead Strike for one target, Split/Swing when safe targets line up. Warbrand is a lighter alternative with different AP costs.",
        masteryNote = "Taken: fatigue savings and accuracy help on Split/Swing.",
        note = "Overhead Strike has +5 accuracy and +20 base damage; area attacks use different bonuses and costs.",
        patterns = [
            {label = "Ordinary attacks; no kill assumed", steps = [{ids = ["actives.overhead_strike"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.sword"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_2h_flail",
        label = "Damage - 2H Flail (Nimble)",
        role = "Two-handed",
        weaponTags = ["Flail"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.flail"],
        niche = "Dedicated 2H Flail damage with Fatigue for repeated attacks.",
        targets = {hp = 80, fatigue = 115, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 130, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.pathfinder", "perk.mastery.flail", "perk.nimble", "perk.head_hunter", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Two-Handed Flail; Pound for single targets. A Berserk Chain has higher Fatigue costs.",
        masteryNote = "Taken: fatigue savings and another 10 percentage points of penetration on Pound headshots.",
        note = "Pound bypasses shield item defence; headshots benefit from mastery. Do not budget Thresh as a reliable multi-target baseline.",
        patterns = [
            {label = "Ordinary attacks; no kill assumed", steps = [{ids = ["actives.pound"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.flail"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_2h_cleaver",
        label = "Damage - 2H Cleaver (Nimble)",
        role = "Two-handed",
        weaponTags = ["Cleaver"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.cleaver"],
        niche = "Dedicated 2H Cleaver damage with Fatigue for repeated attacks.",
        targets = {hp = 80, fatigue = 115, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 130, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.pathfinder", "perk.mastery.cleaver", "perk.nimble", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Two-Handed Scimitar or Rusty Warblade. Decapitate exploits missing HP; bleed needs susceptible enemies.",
        masteryNote = "Taken: fatigue savings and doubled bleed; Disarm needs the separate Whip hybrid loadout.",
        note = "Two ordinary attacks cost 8 AP. Berserk and Recover combinations require an actual 4-AP kill. The Whip hybrid is a separate utility route.",
        patterns = [
            {label = "Ordinary attacks; no kill assumed", steps = [{ids = ["actives.cleave"], count = 2, fat = 12, ap = 4, mastery = "perk.mastery.cleaver"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_sword",
        label = "Duelist - Sword (Nimble)",
        role = "Duelist",
        weaponTags = ["Sword"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.sword", "perk.duelist"],
        niche = "One-handed sword damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 100, resolve = 45, matk = 75, mdef = 30},
        preferred = {hp = 90, fatigue = 115, resolve = 55, matk = 85, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.sword", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Noble Sword; Shamshir is an injury-oriented alternative. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Riposte is conditional on enemies missing, not guaranteed bonus attacks.",
        note = "A buckler retains Duelist but turns off Double Grip. A shield or net changes damage and available actions. Weapon tiers and enemy armour still matter.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.slash"], count = 2, fat = 10, ap = 4, mastery = "perk.mastery.sword"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_axe",
        label = "Duelist - Axe (Nimble)",
        role = "Duelist",
        weaponTags = ["Axe"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.axe", "perk.duelist"],
        niche = "One-handed axe damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.axe", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Fighting Axe; Orc Head Splitter is heavier and costs more Fatigue. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Shield breaking costs time and can give enemies Double Grip; ordinary Chop is the baseline.",
        note = "A buckler retains Duelist but turns off Double Grip. A shield or net changes damage and available actions. Weapon tiers and enemy armour still matter.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.chop"], count = 2, fat = 13, ap = 4, mastery = "perk.mastery.axe"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_mace",
        label = "Duelist - Mace (Nimble)",
        role = "Duelist",
        weaponTags = ["Mace"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.mace", "perk.duelist"],
        niche = "One-handed mace damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.mace", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Winged Mace; stun is a conditional alternative to ordinary Bash. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Stun becomes reliable after a hit against susceptible targets.",
        note = "A buckler retains Duelist but turns off Double Grip. A shield or net changes damage and available actions. Weapon tiers and enemy armour still matter.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.bash"], count = 2, fat = 13, ap = 4, mastery = "perk.mastery.mace"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_hammer",
        label = "Duelist - Hammer (Nimble)",
        role = "Duelist",
        weaponTags = ["Hammer"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.hammer", "perk.duelist"],
        niche = "One-handed hammer damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.hammer", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Warhammer; ordinary Batter exploits penetration. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Destroy Armor improves, but ordinary Batter remains the Duelist baseline.",
        note = "A buckler retains Duelist but turns off Double Grip. Destroy Armor sacrifices penetrating HP damage to strip armour; choose it for team support, not as the damage baseline.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.hammer"], count = 2, fat = 14, ap = 4, mastery = "perk.mastery.hammer"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_cleaver",
        label = "Duelist - Cleaver (Nimble)",
        role = "Duelist",
        weaponTags = ["Cleaver"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.cleaver", "perk.duelist"],
        niche = "One-handed cleaver damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 120, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 135, resolve = 55, matk = 95, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.cleaver", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Military Cleaver; Orc Head Chopper needs extra Fatigue capacity. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Bleeds improve against susceptible targets; Decapitate costs 20 before mastery.",
        note = "A buckler retains Duelist but turns off Double Grip. A shield or net changes damage and available actions. Weapon tiers and enemy armour still matter.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.cleave"], count = 2, fat = 12, ap = 4, mastery = "perk.mastery.cleaver"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "duelist_flail",
        label = "Duelist - Flail (Nimble)",
        role = "Duelist",
        weaponTags = ["Flail"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.flail", "perk.duelist"],
        niche = "One-handed flail damage with Duelist and Double Grip.",
        targets = {hp = 80, fatigue = 115, resolve = 45, matk = 80, mdef = 30},
        preferred = {hp = 90, fatigue = 130, resolve = 55, matk = 90, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.gifted", "perk.mastery.flail", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Flail; Lash targets exposed heads but is expensive. Three-Headed Flail splits damage across three hits. Empty offhand by default.",
        masteryNote = "Taken for repeated-attack Fatigue savings. Lash also bypasses shield item defence; Shieldwall still applies.",
        note = "A buckler retains Duelist but turns off Double Grip. A shield or net changes damage and available actions. Weapon tiers and enemy armour still matter.",
        patterns = [
            {label = "Two ordinary attacks; empty offhand", steps = [{ids = ["actives.flail"], count = 2, fat = 13, ap = 4, mastery = "perk.mastery.flail"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "qatal_duelist",
        label = "Qatal Duelist - Ally-supported (Nimble)",
        role = "Specialist",
        weaponTags = ["Dagger"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.dagger", "perk.duelist"],
        niche = "Fast Deathblow specialist; an ally supplies daze, stun or a net.",
        targets = {hp = 68, fatigue = 90, resolve = 45, initiative = 140, matk = 85, mdef = 22},
        preferred = {hp = 80, fatigue = 105, resolve = 50, initiative = 150, matk = 90, mdef = 30},
        priority = ["matk", "mdef", "initiative", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.dodge", "perk.gifted", "perk.relentless", "perk.mastery.dagger", "perk.nimble", "perk.overwhelm", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Qatal Dagger, empty offhand. A 2H Mace partner can supply daze.",
        masteryNote = "Taken: attacks cost 3 AP and 8 Fatigue. Duelist improves penetration; Relentless protects Initiative as Fatigue builds.",
        note = "Three Deathblows need 9 AP with Dagger Mastery. Enhanced damage requires the target condition and suitable turn order. This route does not spend a perk on Quick Hands.",
        patterns = [
            {label = "Three Deathblows; ally supplies stun/daze/net", steps = [{ids = ["actives.deathblow"], count = 3, fat = 10, ap = 4, mastery = "perk.mastery.dagger"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "puncture_dagger",
        label = "Puncture - Dagger + Shield (Nimble)",
        role = "Specialist",
        weaponTags = ["Dagger", "Shield"],
        stopgap = false,
        flex = ["perk.gifted"],
        identity = ["perk.mastery.dagger"],
        niche = "Accurate, fatigue-intensive armour bypass and armour recovery.",
        targets = {hp = 80, fatigue = 125, resolve = 50, matk = 90, mdef = 30},
        preferred = {hp = 90, fatigue = 140, resolve = 60, matk = 100, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.shield_expert", "perk.mastery.dagger", "perk.nimble", "perk.underdog", "perk.berserk", "perk.fortified_mind", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Rondel Dagger + Shield. Puncture does not damage armour.",
        masteryNote = "Taken: Puncture costs 3 AP and 15 Fatigue. Duelist is skipped because Puncture already ignores armour.",
        note = "Puncture ignores armour but has -15 accuracy, no Double Grip and no headshot damage. Three mastered attacks still cost 45 Fatigue. Piercing resistance applies.",
        patterns = [
            {label = "Three Punctures; armour is bypassed, -15 accuracy", steps = [{ids = ["actives.puncture"], count = 3, fat = 20, ap = 4, mastery = "perk.mastery.dagger"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "fencer",
        label = "Fencer - Fencing Sword (Nimble)",
        role = "Specialist",
        weaponTags = ["Sword"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.sword", "perk.duelist"],
        niche = "Exceptional Initiative and melee accuracy for mobile Lunge attacks.",
        targets = {hp = 68, fatigue = 105, resolve = 40, initiative = 160, matk = 90, mdef = 30},
        preferred = {hp = 80, fatigue = 110, resolve = 50, initiative = 170, matk = 95, mdef = 35},
        priority = ["initiative", "matk", "mdef", "hp", "fatigue", "resolve"],
        route = ["perk.colossus", "perk.recover", "perk.dodge", "perk.relentless", "perk.mastery.sword", "perk.nimble", "perk.berserk", "perk.gifted", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Fencing Sword, empty offhand and light armour; clear landing tiles are required.",
        masteryNote = "Taken: cheaper Lunges. Relentless helps preserve current Initiative; Duelist and Double Grip need appropriate equipment.",
        note = "Lunge scales with current Initiative after equipment and accumulated Fatigue. Natural Initiative is only a fit target; it does not guarantee live damage.",
        patterns = [
            {label = "Two Lunges; clear landing tiles and light loadout", steps = [{ids = ["actives.lunge"], count = 2, fat = 25, ap = 4, mastery = "perk.mastery.sword"}], turns = 2, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "estoc_skewer",
        label = "Estoc - Skewer (Nimble)",
        role = "Specialist",
        weaponTags = ["Estoc", "Dagger"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.dagger"],
        niche = "Initiative-driven armour penetration.",
        targets = {hp = 75, fatigue = 110, resolve = 45, matk = 85, mdef = 30, initiative = 150},
        preferred = {hp = 85, fatigue = 125, resolve = 55, matk = 95, mdef = 40, initiative = 175},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.dodge", "perk.relentless", "perk.gifted", "perk.mastery.dagger", "perk.nimble", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Estoc, a two-handed dagger. Mastered Stab costs 4 AP; Skewer and Perforate cost 5 AP.",
        masteryNote = "Dagger Mastery, not Sword Mastery: enables a 4+5 AP turn. Duelist and Double Grip do not apply to this two-handed weapon.",
        note = "Skewer gains penetration with current Initiative and +20 base damage. Perforate starts with two attacks and gains an extra attack per pre-existing temporary injury. Extra hits and perk procs must not be assumed against healthy or immune targets.",
        patterns = [
            {label = "One Stab + one Skewer; no kill assumed", steps = [{ids = ["actives.estoc_stab"], count = 1, fat = 11, ap = 5, mastery = "perk.mastery.dagger"}, {ids = ["actives.skewer"], count = 1, fat = 25, ap = 6, mastery = "perk.mastery.dagger"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "estoc_perforate",
        label = "Estoc - Perforate (Nimble)",
        role = "Specialist",
        weaponTags = ["Estoc", "Dagger"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.dagger"],
        niche = "Repeated thrusts and injury-supported finishing without an Initiative requirement.",
        targets = {hp = 80, fatigue = 120, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 135, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.pathfinder", "perk.gifted", "perk.mastery.dagger", "perk.nimble", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Estoc, a two-handed dagger. Mastered Stab costs 4 AP; Skewer and Perforate cost 5 AP.",
        masteryNote = "Dagger Mastery, not Sword Mastery: enables a 4+5 AP turn. Duelist and Double Grip do not apply to this two-handed weapon.",
        note = "Skewer gains penetration with current Initiative and +20 base damage. Perforate starts with two attacks and gains an extra attack per pre-existing temporary injury. Extra hits and perk procs must not be assumed against healthy or immune targets.",
        patterns = [
            {label = "One Stab + one Perforate; no kill assumed", steps = [{ids = ["actives.estoc_stab"], count = 1, fat = 11, ap = 5, mastery = "perk.mastery.dagger"}, {ids = ["actives.perforate"], count = 1, fat = 25, ap = 6, mastery = "perk.mastery.dagger"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "pollaxe",
        label = "Pollaxe Fighter (Nimble)",
        role = "Specialist",
        weaponTags = ["Pollaxe", "Polearm"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.polearm"],
        niche = "One-tile polearm with stagger setup and conditional follow-up attacks.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.quick_hands", "perk.mastery.polearm", "perk.nimble", "perk.reach_advantage", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Pollaxe; Billhook can provide two-tile reach using the same mastery.",
        masteryNote = "Polearm Mastery: 5 AP and 12 Fatigue for Smite/Assault. Axe or Hammer Mastery is not the matching mastery.",
        note = "Pollaxe is not a Longaxe. Smite and Assault each cost 5 AP when mastered; doing both needs extra AP or separate turns. Assault gains its second strike only against a staggered target.",
        patterns = [
            {label = "One Pollaxe Smite; no stagger setup assumed", steps = [{ids = ["actives.smite"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Assault; its additional strike needs a staggered target", steps = [{ids = ["actives.assault"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "executioner_sword",
        label = "Finisher - Executioner's Sword (Nimble)",
        role = "Specialist",
        weaponTags = ["Sword"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.sword"],
        niche = "Headshot and wounded-target finishing with a heavy sword.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.steel_brow", "perk.mastery.sword", "perk.nimble", "perk.head_hunter", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Executioner's Sword; Execute and Decapitate have different damage assumptions from Greatsword Overhead Strike.",
        masteryNote = "Sword Mastery: fatigue savings for both attacks. Cleaver Mastery does not replace it.",
        note = "Execute adds 15 headshot chance, not +5 accuracy or +20 base damage. Decapitate scales with missing HP; full-health enemies give no finishing bonus.",
        patterns = [
            {label = "Execute; no kill assumed", steps = [{ids = ["actives.execute"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.sword"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Decapitate a wounded target; damage depends on missing HP", steps = [{ids = ["actives.exesword_decapitate"], count = 1, fat = 20, ap = 6, mastery = "perk.mastery.sword"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "billhook",
        label = "Backliner - Billhook (Nimble)",
        role = "Backline / support",
        weaponTags = ["Polearm"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.polearm"],
        niche = "Protected reach damage with mobility.",
        targets = {hp = 72, fatigue = 100, resolve = 45, matk = 80, mdef = 10},
        preferred = {hp = 80, fatigue = 110, resolve = 55, matk = 90, mdef = 20},
        priority = ["matk", "hp", "fatigue", "resolve", "mdef"],
        route = ["perk.colossus", "perk.pathfinder", "perk.quick_hands", "perk.gifted", "perk.mastery.polearm", "perk.nimble", "perk.dodge", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Billhook; pikes are earlier accuracy alternatives with different piercing resistance.",
        masteryNote = "Taken: polearm actions cost 5 AP, fatigue costs fall and adjacent attack penalties are removed. Longaxe, Polemace and Polehammer use other masteries.",
        note = "Backline defence targets do not certify a frontliner. Reap targets, Fearsome checks and Berserk kills are conditional.",
        patterns = [
            {label = "One Billhook strike; movement remains available", steps = [{ids = ["actives.strike"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "swordlance",
        label = "Backliner - Swordlance / Reaper (Nimble)",
        role = "Backline / support",
        weaponTags = ["Polearm"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.polearm"],
        niche = "Protected reach area damage; Fatigue and target access matter.",
        targets = {hp = 72, fatigue = 115, resolve = 50, matk = 85, mdef = 10},
        preferred = {hp = 80, fatigue = 130, resolve = 65, matk = 95, mdef = 20},
        priority = ["matk", "hp", "fatigue", "resolve", "mdef"],
        route = ["perk.colossus", "perk.pathfinder", "perk.quick_hands", "perk.gifted", "perk.mastery.polearm", "perk.nimble", "perk.dodge", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Swordlance or Warscythe; Billhook is a single-target alternative.",
        masteryNote = "Taken: polearm actions cost 5 AP, fatigue costs fall and adjacent attack penalties are removed. Longaxe, Polemace and Polehammer use other masteries.",
        note = "Backline defence targets do not certify a frontliner. Reap targets, Fearsome checks and Berserk kills are conditional.",
        patterns = [
            {label = "One Reap; safe adjacent targets required", steps = [{ids = ["actives.reap"], count = 1, fat = 30, ap = 6, mastery = "perk.mastery.polearm"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_polearm_banner",
        label = "Banner - Polearm Support (Nimble)",
        role = "Backline / support",
        weaponTags = ["Banner", "Polearm"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.rally_the_troops", "perk.mastery.polearm"],
        niche = "High-Resolve rally support with protected melee reach.",
        targets = {hp = 72, fatigue = 100, resolve = 85, matk = 75},
        preferred = {hp = 85, fatigue = 110, resolve = 100, matk = 85, mdef = 15},
        priority = ["resolve", "matk", "hp", "fatigue", "mdef"],
        route = ["perk.colossus", "perk.pathfinder", "perk.fortified_mind", "perk.rally_the_troops", "perk.mastery.polearm", "perk.nimble", "perk.quick_hands", "perk.gifted", "perk.recover", "perk.fearsome"],
        swaps = [],
        armour = "nimble",
        weapons = "Battle Standard + Billhook. The banner aura is present only while the standard is held.",
        masteryNote = "Polearm Mastery improves banner/reach attacks. Fortified Mind and Rally define the support role.",
        note = "Rally and a mastered banner strike each cost 5 AP, so they do not fit the same ordinary turn. Switching away from the banner removes its aura.",
        patterns = [
            {label = "Rally once per turn; no same-turn banner attack", steps = [{ids = ["actives.rally_the_troops"], count = 1, fat = 25, ap = 5, mastery = ""}], turns = 2, buffer = 0, move = 0, kill = false},
            {label = "Banner strike; no Rally in this cycle", steps = [{ids = ["actives.impale", "actives.strike"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "pure_bow",
        label = "Pure Bow (Nimble)",
        role = "Ranged",
        weaponTags = ["Bow"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.bow"],
        niche = "Dedicated bow use; no melee training required.",
        targets = {hp = 70, fatigue = 100, resolve = 40, ratk = 90},
        preferred = {hp = 80, fatigue = 110, resolve = 50, ratk = 100},
        priority = ["ratk", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.bullseye", "perk.mastery.bow", "perk.nimble", "perk.footwork", "perk.berserk", "perk.head_hunter", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "War Bow and arrows. Quick Shot and Aimed Shot have different accuracy, AP and Fatigue.",
        masteryNote = "Taken: cheaper shots and extra range. Quick Hands solely for arrow stacks is skipped.",
        note = "Stay protected. This route spends no perks or attribute picks on a melee hybrid. Bullseye reduces cover penalties; it does not make shots through allies harmless.",
        patterns = [
            {label = "Two Quick Shots; no kill assumed", steps = [{ids = ["actives.quick_shot"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.bow"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "One Aimed Shot; more accuracy and range reliability", steps = [{ids = ["actives.aimed_shot"], count = 1, fat = 20, ap = 7, mastery = "perk.mastery.bow"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "pure_crossbow",
        label = "Pure Crossbow (Nimble)",
        role = "Ranged",
        weaponTags = ["Crossbow"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.crossbow"],
        niche = "Dedicated crossbow use; no melee training required.",
        targets = {hp = 70, fatigue = 95, resolve = 40, ratk = 80},
        preferred = {hp = 80, fatigue = 105, resolve = 50, ratk = 90},
        priority = ["ratk", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.fast_adaption", "perk.mastery.crossbow", "perk.nimble", "perk.footwork", "perk.berserk", "perk.head_hunter", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Heavy Crossbow and bolts; cannot reload while engaged in melee.",
        masteryNote = "Taken: normal/heavy bolt penetration increases by 20 percentage points, and fatigue costs fall.",
        note = "Stay protected. This route spends no perks or attribute picks on a melee hybrid. Burst attacks require a kill; no second loaded weapon is assumed.",
        patterns = [
            {label = "Shoot + reload; reload requires freedom from melee", steps = [{ids = ["actives.shoot_bolt"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.reload_bolt"], count = 1, fat = 20, ap = 4, mastery = "perk.mastery.crossbow"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "pure_handgonne",
        label = "Pure Handgonne (Nimble)",
        role = "Ranged",
        weaponTags = ["Handgonne"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.crossbow"],
        niche = "Dedicated handgonne use; no melee training required.",
        targets = {hp = 70, fatigue = 105, resolve = 50, ratk = 85},
        preferred = {hp = 80, fatigue = 115, resolve = 65, ratk = 95},
        priority = ["ratk", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.gifted", "perk.fast_adaption", "perk.mastery.crossbow", "perk.nimble", "perk.footwork", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Handgonne and powder; firing plus mastered reload consumes 9 AP. Number of enemies in the cone is conditional.",
        masteryNote = "Taken: reload falls from 9 to 6 AP, allowing fire + reload. Fearsome is ineffective against morale-immune enemies.",
        note = "Stay protected. This route spends no perks or attribute picks on a melee hybrid. Burst attacks require a kill; no second loaded weapon is assumed.",
        patterns = [
            {label = "Fire + reload; no movement in the same ordinary turn", steps = [{ids = ["actives.fire_handgonne"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.reload_handgonne"], count = 1, fat = 20, ap = 9, mastery = "perk.mastery.crossbow"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_thrower",
        label = "Pure Thrower (Nimble)",
        role = "Ranged",
        weaponTags = ["Throwing"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.throwing", "perk.duelist"],
        niche = "Close-range ranged damage; javelins and axes share one training route.",
        targets = {hp = 70, fatigue = 100, resolve = 40, ratk = 80},
        preferred = {hp = 80, fatigue = 105, resolve = 50, ratk = 85},
        priority = ["ratk", "hp", "resolve", "fatigue"],
        route = ["perk.fast_adaption", "perk.colossus", "perk.bags_and_belts", "perk.quick_hands", "perk.mastery.throwing", "perk.nimble", "perk.gifted", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Heavy Javelins and Heavy Throwing Axes. Prefer axes over javelins against Ancient Dead. A buckler or net preserves Duelist.",
        masteryNote = "Throwing Mastery and Duelist are core. Quick Hands switches stacks; no melee requirements are imposed.",
        note = "Throwing gets no Double Grip. Heavy throwing weapons have a -5 item accuracy modifier. Two-tile mastery damage is +30%; three-tile damage is +20%. Keep a clear firing lane.",
        patterns = [
            {label = "Three throws; one kill must fund Berserk", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 3, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 2, buffer = 0, move = 0, kill = true},
            {label = "Two throws without a kill", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "nimble_bow_thrower",
        label = "Hybrid - Bow + Throwing (Nimble)",
        role = "Hybrid",
        weaponTags = ["Bow", "Throwing"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.throwing", "perk.mastery.bow", "perk.duelist"],
        niche = "Long-range bow pressure and close-range throwing; ranged accuracy only.",
        targets = {hp = 70, fatigue = 105, resolve = 40, ratk = 90},
        preferred = {hp = 80, fatigue = 115, resolve = 50, ratk = 100},
        priority = ["ratk", "hp", "resolve", "fatigue"],
        route = ["perk.fast_adaption", "perk.colossus", "perk.quick_hands", "perk.gifted", "perk.mastery.throwing", "perk.nimble", "perk.mastery.bow", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "War Bow, arrows, Heavy Javelins/Axes. Bow blocks the offhand; plan inventory and ammunition before combat.",
        masteryNote = "Both Bow and Throwing masteries are taken; each supports its own action pattern. Duelist applies to the throws, not the bow.",
        note = "Quick Hands gives one free eligible swap per turn. A bow, quiver and throwing stacks consume bag capacity; do not assume room for extra weapons.",
        patterns = [
            {label = "Two Quick Shots; no kill assumed", steps = [{ids = ["actives.quick_shot"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.bow"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "One Aimed Shot; more accuracy and range reliability", steps = [{ids = ["actives.aimed_shot"], count = 1, fat = 20, ap = 7, mastery = "perk.mastery.bow"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Two throws; no kill assumed", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "crossbow_thrower",
        label = "Hybrid - Crossbow + Throwing (Nimble)",
        role = "Hybrid",
        weaponTags = ["Crossbow", "Throwing"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.mastery.crossbow", "perk.mastery.throwing", "perk.duelist"],
        niche = "Ranged armour penetration with throwing fallback; no melee requirement.",
        targets = {hp = 75, fatigue = 105, resolve = 40, ratk = 85},
        preferred = {hp = 85, fatigue = 115, resolve = 50, ratk = 95},
        priority = ["ratk", "fatigue", "hp", "resolve"],
        route = ["perk.bags_and_belts", "perk.pathfinder", "perk.quick_hands", "perk.mastery.crossbow", "perk.mastery.throwing", "perk.nimble", "perk.colossus", "perk.gifted", "perk.fearsome", "perk.duelist"],
        swaps = [],
        armour = "nimble",
        weapons = "Crossbow + ammunition and Heavy Javelins/Axes. Reloading needs 4 AP and cannot happen while engaged.",
        masteryNote = "Crossbow/Firearms and Throwing masteries support separate actions. Duelist benefits throwing. No melee mastery is required.",
        note = "Only the ranged weapon in hand starts loaded. Each preparation/volley example is a separate turn, not a repeating opening. Bag slots, ammo and swaps must be available.",
        patterns = [
            {label = "Shoot + reload; reload requires freedom from melee", steps = [{ids = ["actives.shoot_bolt"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.reload_bolt"], count = 1, fat = 20, ap = 4, mastery = "perk.mastery.crossbow"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Two throws; no kill assumed", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "handgonne_thrower",
        label = "Hybrid - Handgonne + Throwing (Nimble)",
        role = "Hybrid",
        weaponTags = ["Handgonne", "Throwing"],
        stopgap = false,
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.mastery.crossbow", "perk.mastery.throwing", "perk.duelist"],
        niche = "Ranged area pressure with throwing fallback; no melee requirement.",
        targets = {hp = 75, fatigue = 115, resolve = 50, ratk = 85},
        preferred = {hp = 85, fatigue = 125, resolve = 65, ratk = 95},
        priority = ["ratk", "fatigue", "hp", "resolve"],
        route = ["perk.bags_and_belts", "perk.pathfinder", "perk.quick_hands", "perk.mastery.crossbow", "perk.mastery.throwing", "perk.nimble", "perk.colossus", "perk.gifted", "perk.fearsome", "perk.duelist"],
        swaps = [],
        armour = "nimble",
        weapons = "Handgonne + ammunition and Heavy Javelins/Axes. A second Handgonne starts unloaded in the bag.",
        masteryNote = "Crossbow/Firearms and Throwing masteries support separate actions. Duelist benefits throwing. No melee mastery is required.",
        note = "Only the ranged weapon in hand starts loaded. Each preparation/volley example is a separate turn, not a repeating opening. Bag slots, ammo and swaps must be available.",
        patterns = [
            {label = "Fire + reload; no movement in the same ordinary turn", steps = [{ids = ["actives.fire_handgonne"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.reload_handgonne"], count = 1, fat = 20, ap = 9, mastery = "perk.mastery.crossbow"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Two throws; no kill assumed", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "Preparation turn: swap to the bagged unloaded gun and reload it", steps = [{ids = ["actives.reload_handgonne"], count = 1, fat = 20, ap = 9, mastery = "perk.mastery.crossbow"}], turns = 1, buffer = 0, move = 0, kill = false},
            {label = "Later double volley: both guns loaded, one free eligible swap", steps = [{ids = ["actives.fire_handgonne"], count = 2, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}], turns = 1, buffer = 10, move = 0, kill = false},
        ],
    },
    {
        id = "crossbow_billhook",
        label = "Hybrid - Crossbow + Billhook (Nimble)",
        role = "Hybrid",
        weaponTags = ["Crossbow", "Polearm"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.crossbow", "perk.mastery.polearm"],
        niche = "Protected ranged/reach hybrid; both attack attributes matter.",
        targets = {hp = 72, fatigue = 105, resolve = 40, matk = 80, ratk = 80, mdef = 10},
        preferred = {hp = 82, fatigue = 115, resolve = 50, matk = 90, ratk = 90, mdef = 15},
        priority = ["ratk", "matk", "hp", "fatigue", "resolve", "mdef"],
        route = ["perk.colossus", "perk.pathfinder", "perk.quick_hands", "perk.gifted", "perk.mastery.crossbow", "perk.nimble", "perk.mastery.polearm", "perk.berserk", "perk.fearsome", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Heavy Crossbow + Billhook, with bolts and one free eligible swap each turn.",
        masteryNote = "Crossbow Mastery improves penetration; Polearm Mastery makes Billhook cost 5 AP. Quick Hands enables the alternating sequence.",
        note = "Alternate the two turns: one shot every two turns, with a Billhook strike each turn. Reload cannot happen in melee. The AP budget leaves little or no movement.",
        patterns = [
            {label = "Turn A: shoot, free swap, Billhook strike", steps = [{ids = ["actives.shoot_bolt"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.strike"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}], turns = 1, buffer = 0, move = 0, kill = false},
            {label = "Turn B: Billhook strike, free swap, reload", steps = [{ids = ["actives.strike"], count = 1, fat = 15, ap = 6, mastery = "perk.mastery.polearm"}, {ids = ["actives.reload_bolt"], count = 1, fat = 20, ap = 4, mastery = "perk.mastery.crossbow"}], turns = 1, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "thrower_mace",
        label = "Hybrid - Throwing + 2H Mace (Nimble)",
        role = "Hybrid",
        weaponTags = ["Throwing", "Mace"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.throwing", "perk.duelist"],
        niche = "Throwing damage with credible melee fallback; not a frontline certification.",
        targets = {hp = 64, fatigue = 105, resolve = 40, matk = 75, ratk = 85, mdef = 10},
        preferred = {hp = 75, fatigue = 115, resolve = 50, matk = 85, ratk = 90, mdef = 15, initiative = 105},
        priority = ["ratk", "matk", "hp", "fatigue", "resolve", "mdef", "initiative"],
        route = ["perk.colossus", "perk.pathfinder", "perk.quick_hands", "perk.gifted", "perk.mastery.throwing", "perk.nimble", "perk.dodge", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Heavy Javelins/Axes + Two-Handed Mace. The mace blocks the offhand.",
        masteryNote = "Throwing Mastery and Duelist are core. Mace Mastery is skipped for occasional unmastered 15-Fatigue Cudgel attacks.",
        note = "Two throws and a mace attack do not fit one ordinary turn. Mace daze is useful after a hit, but the backline defence target is not enough for sustained frontline contact.",
        patterns = [
            {label = "Two throws from safety", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "One unmastered 2H Mace attack after an eligible free swap", steps = [{ids = ["actives.cudgel"], count = 1, fat = 15, ap = 6, mastery = ""}], turns = 3, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "thrower_banner",
        label = "Hybrid - Banner + Throwing (Nimble)",
        role = "Hybrid",
        weaponTags = ["Banner", "Throwing"],
        stopgap = false,
        flex = ["perk.killing_frenzy"],
        identity = ["perk.rally_the_troops", "perk.mastery.throwing", "perk.duelist"],
        niche = "High Resolve and ranged accuracy for rally plus protected throwing.",
        targets = {hp = 85, fatigue = 110, resolve = 85, ratk = 85},
        preferred = {hp = 95, fatigue = 120, resolve = 100, ratk = 90},
        priority = ["resolve", "ratk", "hp", "fatigue"],
        route = ["perk.colossus", "perk.fortified_mind", "perk.quick_hands", "perk.rally_the_troops", "perk.mastery.throwing", "perk.nimble", "perk.berserk", "perk.fearsome", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Battle Standard + Heavy Javelins/Axes. The standard blocks the offhand.",
        masteryNote = "Throwing Mastery supports ranged damage. Polearm Mastery is skipped because the banner is carried mainly for Rally and its aura.",
        note = "Rally + one throw fits 5+4 AP with one free swap. Switching to throwing removes the banner aura until the standard is held again; do not promise both at once.",
        patterns = [
            {label = "Rally + one throw; eligible free Quick Hands swap", steps = [{ids = ["actives.rally_the_troops"], count = 1, fat = 25, ap = 5, mastery = ""}, {ids = ["actives.throw_javelin", "actives.throw_axe"], count = 1, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 2, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "mace_qatal",
        label = "Hybrid - 2H Mace + Qatal (Nimble)",
        role = "Hybrid",
        weaponTags = ["Mace", "Dagger"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.dagger", "perk.duelist"],
        niche = "Self-supplied daze and one same-turn Qatal follow-up.",
        targets = {hp = 80, fatigue = 110, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 125, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.pathfinder", "perk.quick_hands", "perk.gifted", "perk.mastery.dagger", "perk.nimble", "perk.underdog", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Two-Handed Mace + Qatal Dagger, with empty offhand for Qatal damage.",
        masteryNote = "Dagger Mastery makes Deathblow cost 3 AP. Mace Mastery is skipped: its daze does not need mastery and the route spends the point elsewhere.",
        note = "This is one Deathblow after the 6-AP mace attack, not the ally-supported three-Deathblow turn. A missed mace attack provides no daze. Quick Hands grants only one free swap per turn. This burst starts with the mace held; prepare it again before repeating.",
        patterns = [
            {label = "Cudgel + free swap + one Deathblow; daze needs a landed mace hit", steps = [{ids = ["actives.cudgel"], count = 1, fat = 15, ap = 6, mastery = ""}, {ids = ["actives.deathblow"], count = 1, fat = 10, ap = 4, mastery = "perk.mastery.dagger"}], turns = 1, buffer = 0, move = 0, kill = false},
        ],
    },
    {
        id = "cleaver_whip",
        label = "Hybrid - 2H Cleaver + Whip (Nimble)",
        role = "Hybrid",
        weaponTags = ["Cleaver", "Whip"],
        stopgap = false,
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.cleaver"],
        niche = "Cleaver damage with reach control when an enemy needs disarming.",
        targets = {hp = 80, fatigue = 120, resolve = 45, matk = 85, mdef = 30},
        preferred = {hp = 90, fatigue = 135, resolve = 55, matk = 95, mdef = 40},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.recover", "perk.gifted", "perk.quick_hands", "perk.mastery.cleaver", "perk.nimble", "perk.underdog", "perk.berserk", "perk.reach_advantage", "perk.killing_frenzy"],
        swaps = [],
        armour = "nimble",
        weapons = "Two-Handed Scimitar/Rusty Warblade + Whip. Use the Whip for control, not primary damage.",
        masteryNote = "Cleaver Mastery supports both weapons: Disarm improves from -20 to -10 accuracy and costs 23 Fatigue. Quick Hands enables the 4+5 AP sequence.",
        note = "Disarm needs a hit and a susceptible target. Swapping weapons loses Reach Advantage stacks; control competes with damage and Fatigue.",
        patterns = [
            {label = "Two cleaves; no kill assumed", steps = [{ids = ["actives.cleave"], count = 2, fat = 12, ap = 4, mastery = "perk.mastery.cleaver"}], turns = 3, buffer = 0, move = 0, kill = false},
            {label = "One cleave + free swap + Disarm", steps = [{ids = ["actives.cleave"], count = 1, fat = 12, ap = 4, mastery = "perk.mastery.cleaver"}, {ids = ["actives.disarm"], count = 1, fat = 30, ap = 5, mastery = "perk.mastery.cleaver"}], turns = 1, buffer = 0, move = 0, kill = false},
        ],
    },
];
::BroLedger.findBuild <- function(id)
{
    foreach (build in this.Builds) if (build.id == id) return build;
    return null;
};
