// Original starting guides, not claims of optimal tactics. Never persisted or edited in place.
::BroLedger.StarterBuilds <- [
    {id="starter_shield_tank",label="Shield Tank",
        targets={hp=75,resolve=55,fatigue=110,mdef=30},
        preferred={hp=90,resolve=70,fatigue=130,mdef=40},
        weights={hp=6,resolve=6,fatigue=4,initiative=0,matk=0,ratk=0,mdef=10,rdef=0},
        route=["perk.colossus","perk.gifted","perk.shield_expert","perk.taunt","perk.recover","perk.fortified_mind","perk.nimble","perk.underdog","perk.indomitable","perk.rotation"],
        flex=["perk.gifted"],weaponTags=["Shield","Light armour"],playstyleTags=["Frontline","Tank"]},
    {id="starter_nimble_sword",label="Nimble Sword Frontliner",
        targets={hp=75,resolve=45,fatigue=100,initiative=95,matk=75,mdef=20},
        preferred={hp=90,resolve=55,fatigue=115,initiative=115,matk=85,mdef=30},
        weights={hp=6,resolve=3,fatigue=2,initiative=2,matk=10,ratk=0,mdef=8,rdef=0},
        route=["perk.colossus","perk.dodge","perk.gifted","perk.quick_hands","perk.mastery.sword","perk.underdog","perk.nimble","perk.berserk","perk.killing_frenzy","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Sword","Two-handed","Light armour"],playstyleTags=["Frontline","Damage"]},
    {id="starter_forged_hammer",label="Forged Hammer Two-Hander",
        targets={hp=70,resolve=45,fatigue=115,matk=80,mdef=25},
        preferred={hp=85,resolve=60,fatigue=130,matk=90,mdef=35},
        weights={hp=6,resolve=3,fatigue=5,initiative=0,matk=10,ratk=0,mdef=8,rdef=0},
        route=["perk.colossus","perk.gifted","perk.steel_brow","perk.mastery.hammer","perk.brawny","perk.underdog","perk.battle_forged","perk.berserk","perk.killing_frenzy","perk.recover"],
        flex=["perk.gifted"],weaponTags=["Hammer","Two-handed","Heavy armour"],playstyleTags=["Frontline","Damage"]},
    {id="starter_fatigue_neutral",label="Fatigue Neutral Mace",
        targets={hp=75,resolve=50,fatigue=100,matk=80,mdef=25},
        preferred={hp=90,resolve=65,fatigue=110,matk=90,mdef=35},
        weights={hp=6,resolve=4,fatigue=2,initiative=0,matk=10,ratk=0,mdef=8,rdef=0},
        route=["perk.colossus","perk.pathfinder","perk.gifted","perk.mastery.mace","perk.steel_brow","perk.underdog","perk.battle_forged","perk.quick_hands","perk.fortified_mind","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Mace","Two-handed","Heavy armour"],playstyleTags=["Frontline","Damage"]},
    {id="starter_cleaver_whip",label="Cleaver / Whip",
        targets={hp=75,resolve=45,fatigue=110,matk=80,mdef=20},
        preferred={hp=90,resolve=55,fatigue=125,matk=90,mdef=30},
        weights={hp=6,resolve=3,fatigue=5,initiative=0,matk=10,ratk=0,mdef=6,rdef=0},
        route=["perk.colossus","perk.recover","perk.gifted","perk.quick_hands","perk.mastery.cleaver","perk.underdog","perk.nimble","perk.berserk","perk.killing_frenzy","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Cleaver","Whip","Two-handed","Light armour"],playstyleTags=["Frontline","Damage","Control"]},
    {id="starter_sword_duelist",label="Sword Duelist",
        targets={hp=75,resolve=45,fatigue=110,initiative=95,matk=80,mdef=25},
        preferred={hp=90,resolve=55,fatigue=125,initiative=115,matk=90,mdef=35},
        weights={hp=6,resolve=3,fatigue=5,initiative=2,matk=10,ratk=0,mdef=8,rdef=0},
        route=["perk.colossus","perk.dodge","perk.gifted","perk.mastery.sword","perk.recover","perk.underdog","perk.nimble","perk.berserk","perk.duelist","perk.killing_frenzy"],
        flex=["perk.gifted"],weaponTags=["Sword","Light armour"],playstyleTags=["Frontline","Damage","Duelist"]},
    {id="starter_thrower",label="Thrower",
        targets={hp=65,resolve=40,fatigue=100,ratk=75},
        preferred={hp=80,resolve=50,fatigue=115,ratk=85},
        weights={hp=4,resolve=2,fatigue=3,initiative=0,matk=0,ratk=10,mdef=0,rdef=0},
        route=["perk.colossus","perk.quick_hands","perk.gifted","perk.bags_and_belts","perk.mastery.throwing","perk.footwork","perk.nimble","perk.berserk","perk.duelist","perk.killing_frenzy"],
        flex=["perk.gifted"],weaponTags=["Throwing","Light armour"],playstyleTags=["Backline","Damage","Ranged"]},
    {id="starter_archer",label="Archer",
        targets={hp=60,resolve=40,fatigue=100,ratk=80},
        preferred={hp=75,resolve=50,fatigue=115,ratk=90},
        weights={hp=4,resolve=2,fatigue=3,initiative=0,matk=0,ratk=10,mdef=0,rdef=0},
        route=["perk.colossus","perk.bullseye","perk.gifted","perk.pathfinder","perk.mastery.bow","perk.footwork","perk.nimble","perk.berserk","perk.killing_frenzy","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Bow","Light armour"],playstyleTags=["Backline","Damage","Ranged"]},
    {id="starter_crossbow_polearm",label="Crossbow / Polearm Hybrid",
        targets={hp=65,resolve=40,fatigue=105,matk=70,ratk=70,mdef=10},
        preferred={hp=80,resolve=50,fatigue=120,matk=80,ratk=80,mdef=20},
        weights={hp=5,resolve=2,fatigue=4,initiative=0,matk=8,ratk=8,mdef=2,rdef=0},
        route=["perk.colossus","perk.quick_hands","perk.gifted","perk.mastery.crossbow","perk.mastery.polearm","perk.footwork","perk.nimble","perk.berserk","perk.killing_frenzy","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Crossbow","Polearm","Light armour"],playstyleTags=["Backline","Damage","Hybrid"]},
    {id="starter_banner",label="Banner Sergeant",
        targets={hp=70,resolve=80,fatigue=105,matk=65,mdef=10},
        preferred={hp=85,resolve=100,fatigue=120,matk=75,mdef=20},
        weights={hp=5,resolve=10,fatigue=4,initiative=0,matk=3,ratk=0,mdef=2,rdef=0},
        route=["perk.colossus","perk.fortified_mind","perk.gifted","perk.rally_the_troops","perk.recover","perk.mastery.polearm","perk.nimble","perk.quick_hands","perk.footwork","perk.fearsome"],
        flex=["perk.gifted"],weaponTags=["Polearm","Light armour"],playstyleTags=["Backline","Support"]},
];
