// Owned revision-2 snapshots for saved-intent continuity; not shipped.
return {
    nimble_2h_berserk = {
        id = "nimble_2h_berserk",
        label = "2H Nimble + Dodge - Axe/Mace/Hammer",
        flex = ["perk.pathfinder", "perk.killing_frenzy"],
        identity = ["perk.nimble", "perk.berserk", "perk.mastery.axe"],
        focus = ["fatigue", "mdef"],
        specializes = ["dodge_qh_axe"],
        niche = "Light-armour 2H damage with Fatigue and defence for repeated attacks.",
        targets = {hp = 80, fatigue = 110, resolve = 50, matk = 85, mdef = 35},
        preferred = {hp = 90, fatigue = 120, resolve = 55, matk = 90, mdef = 40, initiative = 110},
        priority = ["matk", "mdef", "hp", "resolve", "fatigue", "initiative"],
        route = ["perk.colossus", "perk.pathfinder", "perk.dodge", "perk.quick_hands", "perk.gifted", "perk.nimble", "perk.mastery.axe", "perk.underdog", "perk.berserk", "perk.killing_frenzy"],
        swaps = [{replace = "perk.mastery.axe", with = "perk.mastery.mace", condition = "the final weapon pair is Two-Handed Mace/Polemace"}, {replace = "perk.mastery.axe", with = "perk.mastery.hammer", condition = "MDef, Fatigue and a flank position justify a Two-Handed Hammer"}],
        armour = "nimble",
        weapons = "Greataxe + Longaxe; swap the mastery as a block if the final destination is Mace or Hammer.",
        note = "Prefer Hammer only with strong MDef and Fatigue for a flank position; Axe or Mace is safer in the centre. Do not lock a mastery before the final weapon and position are decided.",
        patterns = [{label = "Two single-target 2H attacks; one kill must fund Berserk", steps = [{ids = ["actives.split_man", "actives.cudgel", "actives.smite"], count = 2, fat = 15, ap = 6, mastery = "perk.mastery.axe"}], turns = 3, buffer = 0, move = 0, kill = true}],
    },
    qatal_duelist = {
        id = "qatal_duelist",
        label = "Nimble Qatal Duelist",
        flex = ["perk.gifted", "perk.killing_frenzy"],
        identity = ["perk.mastery.dagger", "perk.relentless", "perk.duelist"],
        focus = ["initiative"],
        specializes = ["dodge_qh_axe"],
        niche = "Initiative burst specialist with Quick Hands; needs daze, stun or net support.",
        targets = {hp = 68, fatigue = 90, resolve = 45, initiative = 140, matk = 85, mdef = 22},
        preferred = {hp = 80, fatigue = 105, resolve = 50, initiative = 150, matk = 90, mdef = 30},
        priority = ["matk", "mdef", "initiative", "hp", "resolve", "fatigue"],
        route = ["perk.colossus", "perk.dodge", "perk.quick_hands", "perk.relentless", "perk.mastery.dagger", "perk.nimble", "perk.gifted", "perk.berserk", "perk.duelist", "perk.killing_frenzy"],
        swaps = [{replace = "perk.gifted", with = "perk.overwhelm", condition = "the base stats already meet the minimums and high Initiative supports control"}, {replace = "perk.killing_frenzy", with = "perk.fearsome", condition = "morale control is more useful than the post-kill damage spike"}],
        armour = "nimble",
        weapons = "Qatal Dagger; coordinate Deathblow with a Two-Handed Mace partner or a pocket weapon.",
        note = "A specialist route requiring real Initiative and team coordination. Do not recommend it merely because Initiative has stars. Default includes Quick Hands for pocket-weapon flexibility; teammate-supported Qatal is a different setup. Daze/stun/net support and actual turn order are required for the intended burst; a pocket mace is not free same-turn setup.",
        patterns = [{label = "Three Deathblows; ally supplies stun/daze/net", steps = [{ids = ["actives.deathblow"], count = 3, fat = 10, ap = 4, mastery = "perk.mastery.dagger"}], turns = 3, buffer = 0, move = 0, kill = false}],
    },
    double_gunner = {
        id = "double_gunner",
        label = "Nimble Double Gunner/Thrower",
        flex = ["perk.gifted", "perk.pathfinder"],
        identity = ["perk.mastery.crossbow", "perk.mastery.throwing", "perk.fearsome"],
        focus = ["fatigue", "ratk"],
        specializes = ["nimble_thrower", "tempo_hybrid_thrower"],
        niche = "Melee-capable gunner/thrower; two guns, ammunition and volley setup are conditional.",
        targets = {hp = 75, fatigue = 115, resolve = 35, matk = 80, ratk = 85, mdef = 15},
        preferred = {hp = 85, fatigue = 125, resolve = 50, matk = 85, ratk = 90, mdef = 20},
        priority = ["ratk", "matk", "fatigue", "hp", "mdef", "resolve"],
        route = ["perk.bags_and_belts", "perk.pathfinder", "perk.quick_hands", "perk.mastery.crossbow", "perk.mastery.throwing", "perk.nimble", "perk.colossus", "perk.gifted", "perk.fearsome", "perk.duelist"],
        swaps = [{replace = "perk.gifted", with = "perk.berserk", condition = "the base stats are already safe and usable Fatigue supports kill sequences"}],
        armour = "nimble",
        weapons = "Two Handgonnes + Heavy Javelins/Axes; late route that depends on equipment and ammunition.",
        note = "Melee-capable gunner/thrower subtype: MAtk 80 and MDef 15 are deliberate. Opening volley needs two loaded guns, ammunition and a free eligible swap.",
        patterns = [{label = "Fire + reload one Handgonne", steps = [{ids = ["actives.fire_handgonne"], count = 1, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}, {ids = ["actives.reload_handgonne"], count = 1, fat = 20, ap = 9, mastery = "perk.mastery.crossbow"}], turns = 3, buffer = 0, move = 0, kill = false}, {label = "Opening volley: two loaded guns + eligible free swap", steps = [{ids = ["actives.fire_handgonne"], count = 2, fat = 5, ap = 3, mastery = "perk.mastery.crossbow"}], turns = 1, buffer = 10, move = 0, kill = false}, {label = "Throwing fallback", steps = [{ids = ["actives.throw_javelin", "actives.throw_axe"], count = 2, fat = 15, ap = 4, mastery = "perk.mastery.throwing"}], turns = 3, buffer = 0, move = 0, kill = false}],
    },
};
